apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "manifests.fullname" . }}-web-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
