apiVersion: v1
kind: Service
metadata:
  name: {{ include "manifests.fullname" . }}-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
