package generator

const chartYAMLTemplate = `apiVersion: v2
name: {{ .Name }}
description: Helm chart generated by helmify for {{ .Name }}
type: application
version: 0.1.0
appVersion: "1.0.0"
`

const helmignoreTemplate = `.git/
.gitignore
*.swp
*.bak
.DS_Store
`

const helpersTemplate = `{{ "{{-" }} define "{{ .Name }}.fullname" -{{ "}}" }}
{{ "{{-" }} .Release.Name -{{ "}}" }}-{{ "{{" }} .Chart.Name {{ "}}" }}
{{ "{{-" }} end {{ "}}" }}

{{ "{{-" }} define "{{ .Name }}.labels" -{{ "}}" }}
app.kubernetes.io/name: {{ "{{" }} .Chart.Name {{ "}}" }}
app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
app.kubernetes.io/managed-by: {{ "{{" }} .Release.Service {{ "}}" }}
{{ "{{-" }} end {{ "}}" }}
`

const notesTemplate = `helmify generated this chart for "{{ .Name }}".

Workloads deployed:
{{ range .Workloads }}  - {{ .Kind }}/{{ .Name }}
{{ end }}
Run "kubectl get pods -l app.kubernetes.io/instance={{ "{{" }} .Release.Name {{ "}}" }}" to check status.
`

// values.yaml aggregates one values block per workload, keyed by sanitized name.
const valuesYAMLTemplate = `# values.yaml generated by helmify
{{ range .Workloads }}{{ $name := .Name }}
{{ $name }}:
  replicaCount: {{ .Replicas }}
  image:
    repository: {{ .Container.Image | default "REPLACE_ME/image" }}
    tag: "{{ .Container.Tag | default "latest" }}"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "{{ .Container.Resources.RequestsCPU | default "100m" }}"
      memory: "{{ .Container.Resources.RequestsMemory | default "128Mi" }}"
    limits:
      cpu: "{{ .Container.Resources.LimitsCPU | default "500m" }}"
      memory: "{{ .Container.Resources.LimitsMemory | default "512Mi" }}"
  env:
{{ range .Container.Env }}    - name: {{ .Name }}
      value: "{{ .Value }}"
{{ end }}  ports:
{{ range .Container.Ports }}    - name: {{ .Name | default "http" }}
      containerPort: {{ .ContainerPort }}
      protocol: {{ .Protocol }}
{{ end }}{{ end }}
`

const workloadTemplate = `apiVersion: apps/v1
kind: {{ .Workload.Kind }}
metadata:
  name: {{ "{{" }} include "{{ .Project.Name }}.fullname" . {{ "}}" }}-{{ .Workload.Name }}
  labels:
    {{ "{{-" }} include "{{ .Project.Name }}.labels" . | nindent 4 {{ "}}" }}
spec:
  replicas: {{ "{{" }} .Values.{{ .Workload.Name }}.replicaCount {{ "}}" }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Workload.Name }}
      app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Workload.Name }}
        app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
    spec:
{{- if .Secure }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
{{- end }}
      containers:
        - name: {{ .Workload.Container.Name | default .Workload.Name }}
          image: "{{ "{{" }} .Values.{{ .Workload.Name }}.image.repository {{ "}}" }}:{{ "{{" }} .Values.{{ .Workload.Name }}.image.tag {{ "}}" }}"
          imagePullPolicy: {{ "{{" }} .Values.{{ .Workload.Name }}.image.pullPolicy {{ "}}" }}
{{- if .Secure }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- end }}
{{- if .Workload.Container.Ports }}
          ports:
{{ range .Workload.Container.Ports }}            - name: {{ .Name | default "http" }}
              containerPort: {{ .ContainerPort }}
              protocol: {{ .Protocol }}
{{ end }}{{- end }}
{{- if .Workload.Container.Env }}
          env:
{{ range .Workload.Container.Env }}            - name: {{ .Name }}
              value: "{{ .Value }}"
{{ end }}{{- end }}
          resources:
            requests:
              cpu: {{ "{{" }} .Values.{{ .Workload.Name }}.resources.requests.cpu {{ "}}" }}
              memory: {{ "{{" }} .Values.{{ .Workload.Name }}.resources.requests.memory {{ "}}" }}
            limits:
              cpu: {{ "{{" }} .Values.{{ .Workload.Name }}.resources.limits.cpu {{ "}}" }}
              memory: {{ "{{" }} .Values.{{ .Workload.Name }}.resources.limits.memory {{ "}}" }}
`

const networkPolicyTemplate = `apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ "{{" }} include "{{ .Project.Name }}.fullname" . {{ "}}" }}-{{ .Workload.Name }}-default-deny
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Workload.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
`

const serviceTemplate = `apiVersion: v1
kind: Service
metadata:
  name: {{ "{{" }} include "{{ .Project.Name }}.fullname" . {{ "}}" }}-{{ .Service.Name }}
spec:
  type: {{ .Service.Type }}
  selector:
    app.kubernetes.io/instance: {{ "{{" }} .Release.Name {{ "}}" }}
  ports:
    - port: {{ .Service.Port }}
      targetPort: {{ .Service.TargetPort }}
      protocol: {{ .Service.Protocol }}
`

const configMapTemplate = `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ "{{" }} include "{{ .Project.Name }}.fullname" . {{ "}}" }}-{{ .ConfigMap.Name }}
data:
{{ range $k, $v := .ConfigMap.Data }}  {{ $k }}: "{{ $v }}"
{{ end }}
`

const ingressTemplate = `apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ "{{" }} include "{{ .Project.Name }}.fullname" . {{ "}}" }}-{{ .Ingress.Name }}
spec:
  rules:
    - host: {{ .Ingress.Host }}
      http:
        paths:
          - path: {{ .Ingress.Path }}
            pathType: Prefix
            backend:
              service:
                name: {{ "{{" }} include "{{ .Project.Name }}.fullname" . {{ "}}" }}-{{ .Ingress.Name }}
                port:
                  number: {{ .Ingress.Port }}
`
